import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./context/AuthProvider";
import { signOut, useSession } from "next-auth/react";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Sidebar from "./components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  /*   const { data: session, status } = useSession();
  const val: any = session?.user;

  if (val?.role != "ADMIN") return <span>Vous netes pas ADMIN</span>; */

  console.log("OSSSSSSSSS");

  return (
    <html lang="en">
      <body
        className="bg-gray-100 text-third sm:mx-40 h-screen flex flex-col justify-between"
        suppressHydrationWarning={true}
      >
        <AuthProvider>
          {/*           <Header />
           */}{" "}
          <div className="h-full flex">
            <div className="max-md:hidden w-1/4 h-full">
              <Sidebar />
            </div>
            <div className="bg-slate-200 w-full my-2 rounded-lg p-2">
              {children}
            </div>
          </div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
